name: Segreduino
description: "Segreduino is an automated waste segregation and bin-level monitoring system integrated with IoT and a mobile dashboard for real-time monitoring."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.9.0
  shared_preferences: ^2.2.2
  crypto: ^3.0.2
  http: ^1.6.0
  cupertino_icons: ^1.0.8
  image_picker: ^1.0.7   # <--- Add this for image picking
  pdf: ^3.10.4
  csv: ^5.1.0
  path_provider: ^2.1.2
  permission_handler: ^11.3.1
  intl: ^0.20.2
  google_sign_in: ^6.1.6
  percent_indicator: ^4.2.2
  google_fonts: ^8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/sereg.png
    - assets/google_logo.png
    - assets/biode.png
    - assets/NONBIO.png
    - assets/RECYCLE.png
    - assets/biodegradable_bin.png
    - assets/recyclable_bin.png
    - assets/non_biodegradable_bin.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/sereg.png"

